name: ResistorDecoder
version: "1.0"
summary: GUI tool for through-hole resistors and SMD parts.
description: |
  This is a standalone Qt GUI tool for color bands on through-hole resistors 
  and number codes on SMD parts. It supports 3, 4, 5, and 6 band resistors, 
  as well as standard SMD codes, including the EIA-96 standard.

base: core18
grade: stable
confinement: strict
icon: icons/resistor_decoder.png

apps:
  resistor_decoder:
    command: resistor_decoder $SNAP/bin/resistor_decoder
    plugs:
      - home

parts:
  resistor_decoder:
    plugin: python
    source: .
    stage-packages:
        - xsel
        - python3-pyside6
        - libgeos-3.6.2